# Generated by Django 4.1.4 on 2023-03-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_alter_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='provider_order_id',
        ),
    ]
