# Generated by Django 4.1.4 on 2023-03-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_alter_cartlist_provider_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartlist',
            name='provider_order_id',
        ),
        migrations.RemoveField(
            model_name='cartlist',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='cartlist',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='cartlist',
            name='razor_pay_payment_signature',
        ),
        migrations.RemoveField(
            model_name='cartlist',
            name='status',
        ),
    ]
