# Generated by Django 3.2.15 on 2022-11-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique='true')),
                ('slug', models.SlugField(max_length=200, unique='true')),
                ('image', models.ImageField(upload_to='products')),
                ('desc', models.TextField()),
                ('stock', models.IntegerField()),
                ('available', models.BooleanField()),
                ('review', models.TextField()),
                ('star', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
