# Generated by Django 3.2.15 on 2022-11-15 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='shop_app.categ'),
            preserve_default=False,
        ),
    ]
