# Generated by Django 3.2.15 on 2022-11-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20221115_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='shop_app.categ'),
        ),
    ]
