# Generated by Django 3.2.15 on 2022-11-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_alter_products_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_app.categ'),
        ),
    ]
