# Generated by Django 3.2.15 on 2022-11-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_alter_products_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='actualprice',
        ),
        migrations.AddField(
            model_name='products',
            name='currentprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='offer_val',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
