# Generated by Django 3.2.15 on 2022-11-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20221116_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='actualprice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='currentprice',
        ),
    ]
