# Generated by Django 3.2.15 on 2022-11-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default='All', on_delete=django.db.models.deletion.CASCADE, to='shop_app.categ'),
        ),
    ]
